project_id = "vttozwaoksrlgqlimilt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"
buckets = []

[edge_functions]
enabled = true
port = 54323

[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false