// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vttozwaoksrlgqlimilt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0dG96d2Fva3NybGdxbGltaWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDM1NjUsImV4cCI6MjA2NjE3OTU2NX0.iR5SICaRKGdkO5-NXo0hZZgJjck3VNX-yDv56A-KBH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);